version: "3"
volumes:
  psql:
services:
  psql:
    image: postgres # this uses the 'latest' version
    environment:
      POSTGRES_PASSWORD: example # only do this in development
    volumes:
      - psql:/var/lib/postgresql/data # save data between restarts
    ports:
      - "5432:5432"
